---
- name: Install docker on Ubuntu vm2
  hosts: vm2
  gather_facts: false
  remote_user: ansible
  become: true
  roles:
   - docker-ubuntu

- name: Install docker on CentOS 8 vm3
  hosts: vm3
  gather_facts: false
  remote_user: ansible
  become: true
  roles:
   - docker-centos

- name: Install postgressql on Ubuntu vm1
  hosts: database
  gather_facts: false
  become: true
  roles:
   - postgresql
