---
# tasks file for docker-ubuntu
- name: Update
  become: true
  apt:
    update_cache: true
    force_apt_get: true

- name: Install docker
  become: true
  package:
    name: docker
    state: latest

- name: Install docker.io
  become: true
  package:
    name: docker.io
    state: latest

- name: Docker start
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted
